# Generated by Django 2.0 on 2019-12-08 11:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0002_bankmembers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankmembers',
            unique_together={('bank_member', 'bank_group')},
        ),
    ]
