# Generated by Django 2.0 on 2019-12-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_debt',
        ),
    ]
